### ISSUE TITLE
Publish version v0.4.0

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#115]
After https://github.com/extendr/libR-sys/pull/113 gets merged, I think it's time to publish it as a new version.

**Comment by CGMossa** [comment]
I believe what happens now is even releases of `ExtendR` depends on the github-hosted version of this crate.

**Comment by yutannihilation** [comment]
Sure. Maybe this should be 0.4.0 for consistency with the extendr version?

**Comment by multimeric** [comment]
I agree that consistency would be good. Do you need help with anything? This crate isn't really my area.

**Comment by eitsupi** [comment]
A related question, I am wondering if moving libR-sys to a subdirectory of extendr would make it easier to manage.
I saw such a structure in the duckdb-rs repo.
https://github.com/wangfenjin/duckdb-rs

Since Rust 1.64 or later allows the version number etc. to be inherited throughout the workspace, it would reduce the effort of specifying the version in multiple places.

**Comment by CGMossa** [comment]
@eitsupi o agree with you that this is an option. But this binding project is very useful on its own to people that may want to do things without extendr.
Plus there is so much crap with this package all the time, that @yutannihilation and a few others deal with, that it will be unbearable if they had to also have the burden of the extendr workspace on top.

For now, let's keep them separate still.

**Comment by yutannihilation** [comment]
I created a pull request for updating the changelog. 

https://github.com/extendr/libR-sys/pull/138/files

If this is good, I will

- [ ] Merge the pull request
- [ ] Create tag `v0.4.0`
- [ ] Publish to Crates.io
- [ ] Create a GitHub release

**Comment by yutannihilation** [comment]
I'll publish the release 12 hours later or so, so please comment if there's any concern.

**Comment by multimeric** [comment]
Sounds good, thanks!

**Comment by yutannihilation** [comment]
v0.4.0 is now on crates.io. Thank you for all your help!
