### ISSUE TITLE
Segfault calling Rf_pnt from Rmath.h

### ISSUE THREAD

**Issue by ljcolling** [extendr/libR-sys#128]
This issue is currently only applicable to the branch containing the Rmath.h binding.

Currently, the `Rf_pnt()` function will segfault when large negative values are passed to the third argument (`ncp` in `R`)

For example, 

```rust
unsafe{Rf_pnt(0.0, 10.0, -8.0, true as c_int, false as c_int)};
```

will segfault.

The expected behaviour for this call should be printing out the following warning (this calls into `REprintf`)

```
full precision may not have been achieved in 'pnt{final}'
```

and returning a value of approximately  0.9999999999999993

Note: You can work around this issue by flipping the sign of the 1st and 3rd argument or calling 

```rust
unsafe{1.0 - Rf_pnt(0.0, 10.0, -8.0, false as c_int, false as c_int)};
```

so maybe it's not a huge priority, but it is something that is annoying me.

**Comment by Ilia-Kosenkov** [comment]
A wild guess, but do you call this function when R session is running?
Or better yet, can you provide a minimum reproducible example of your problem so we could test it?

**Comment by ljcolling** [comment]
No, R session is running. 
In terms of a minimal example, 

You could just add the following test to `lib.rs`

```rust
    #[test]
    fn test_pnt() {
        unsafe {
            let value1 = unsafe { Rf_pnt(0.0, 10.0, -8.0, true as std::ffi::c_int, false as std::ffi::c_int) };
            let value2 = unsafe {1.0 - Rf_pnt(0.0, 10.0, -8.0, false as std::ffi::c_int, false as std::ffi::c_int) };
            assert_eq!(value1, value2)
        }
    }
```

**Comment by ljcolling** [comment]
actually, it seems that the following test does pass

```rust
    #[test]
    fn test_pnt() {
        start_R();
        unsafe {
            let value1 = unsafe { Rf_pnt(0.0, 10.0, -8.0, true as std::ffi::c_int, false as std::ffi::c_int) };
            let value2 = unsafe {1.0 - Rf_pnt(0.0, 10.0, -8.0, false as std::ffi::c_int, false as std::ffi::c_int) };
            assert_eq!(value1, value2)
        }
    }
```

**Comment by Ilia-Kosenkov** [comment]
Ah, I see, you need to wrap the body of your function into `test! {}` block from `extendr_api`. This ensures there is an R session created for this task and safely terminated at the end.

Now it makes sense -- in your original case, when you hit the happy path, it was just some weird math and it worked fine, but on the unhappy path you called into R-specific functions for displaying warnings and stuff, and this failed miserably without an actual running R session.

**Comment by ljcolling** [comment]
ah okay, that makes sense.
