### ISSUE TITLE
Replace `MSYS2` with native `LLVM` + `RTools`

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#152]
While investigating #151 , I managed to generate bindings using native `LLVM` installation without relying on `MSYS2`. I used `RTools` to provide C/C++ standard headers (`LLVM` does not bundle it apparently), and it worked like a charm. It even worked for old version of R, I was able to generate 32-bit bindings using for R 3.6.3. 
The requirements are:
- `choco` installation of `LLVM` (which sets up path correctly)
- `mingw gcc` on path (`Rtools/blah-blah/bin`)
  - if we want to use `ucrt` version, then we need a `.cargo/config` and linker for `x86_64` set to `x86_64-w64-mingw32.static.posix-gcc.exe`
- `LIBRSYS_LIBCLANG_INCLUDE_PATH` to point to standard `C/C++` headers (also, `Rtools/blah-blah/include`)

Here `blah-blah` is `x86_64-w64-mingw32.static.posix` when a newer version of `Rtools` & 64-bit only R are used, and `mingw64` for older versions, and `mingw32` if we target 32-bit.

**Comment by yutannihilation** [comment]
The official guide recommends winget, btw.

https://rust-lang.github.io/rust-bindgen/requirements.html#windows

**Comment by Ilia-Kosenkov** [comment]
I suspect because MS pushes `winget` or because `LLVM` people maintain `winget` package, but `chocolatey` is community-maintained. The GH runner by default has `LLVM 15.0.7` btw, so we can just run it as is for now https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by yutannihilation** [comment]
I just thought it's the safest to follow what the official recommends, but I just found they don't test Windows at all..., so please ignore my comment.

https://github.com/rust-lang/rust-bindgen/blob/main/.github/workflows/bindgen.yml
