### ISSUE TITLE
LLVM 15 vs LLVM 16

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#158]
There is a notable difference between bindings generated for R-devel on Windows using LLVM 15 and 16 https://github.com/extendr/libR-sys/commit/37a9308397e522eb0f567adbdc4b989a431881fa#diff-8947b0fab22b59ced03f257b9a3d0db60aa68c5ebba8ec1c7131e2ba17103387

Following the discussion in #153 , we decided to use readily available version of LLVM, which is currently `15.0.7`.

The question is, should we force `16.0.1` or higher given this delta?

Pinging @yutannihilation  and @CGMossa.

**Comment by CGMossa** [comment]
I've tried to find a reason to adopt the latest version of LLVM.
Unfortunately, there isn't any concrete ones.
And I don't even know what these changes imply. 
Latest versions of CI runners don't even include it by default. We use the ubuntu one, and it is on 15.
The packages we use `clang-rs`, etc. don't particularly support something that requires this version yet.

**Comment by yutannihilation** [comment]
> a notable difference

Does the difference matter? Either looks fine to me.

> The question is, should we force `16.0.1` or higher given this delta?

We can just wait. I think the runner uses chocolatey to install LLVM, so it will be >16 in the next image.
