### ISSUE TITLE
 Path determination fails on Windows

### ISSUE THREAD

**Issue by clauswilke** [extendr/libR-sys#16]
If `R_HOME` isn't set, we try to find the path to R by executing these lines:
https://github.com/extendr/libR-sys/blob/887b9aab97b6f5163c358193641fca4661fc992c/build.rs#L54

However, this doesn't work, because Windows mangles the paths. See here:
https://github.com/extendr/extendr/issues/67#issuecomment-741190771

Thanks to @Ilia-Kosenkov for discovering this. If we can find a way for R to print a valid Windows path we can fix this problem. Otherwise, `R_HOME` needs to be set for Windows builds to succeed.

**Comment by lebensterben** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamea

**Comment by lebensterben** [comment]
`R.home` calls an internal `R.home` method:
https://github.com/wch/r-source/blob/bcd5629813f4e82c965a07280288423f3a758362/src/library/base/R/files.R#L19-L36

which calls the C function `R_Home`:
https://github.com/wch/r-source/blob/bcd5629813f4e82c965a07280288423f3a758362/src/main/names.c#L799

that in term calls `R_HomeDir`:
https://github.com/wch/r-source/blob/bcd5629813f4e82c965a07280288423f3a758362/src/main/platform.c#L1462-L1469

well, eventually it check the environment variable `R_HOME`
https://github.com/wch/r-source/blob/bcd5629813f4e82c965a07280288423f3a758362/src/main/sysutils.c#L225-L228

I'm not sure why calling `R.home` will have different result from checking `R_HOME` directly.

**Comment by clauswilke** [comment]
This appears to have been resolved with #18.
