### ISSUE TITLE
Run bindings tests on freshly generated bindings

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#162]
TBD

**Comment by CGMossa** [comment]
Do you mean `extendr`?

**Comment by Ilia-Kosenkov** [comment]
Now that is embarrassing, I cannot recall what I meant by this issue. I suspect I wanted to correctly run `libR-sys` tests on freshly generated bindings.

**Comment by CGMossa** [comment]
That's already what happens in CI. Can we close this then?
