### ISSUE TITLE
Suggest moving R configuration querying into a separate crate

### ISSUE THREAD

**Issue by bnaras** [extendr/libR-sys#166]
Just recently had a good reason to use some code from here for a [package](https://crates.io/crates/r-src) for R BLAS+LAPACK . Thank you. 

It appears to me some of the code in the `build.rs` here really belongs in another crate that would be very useful in build scripts. I've put up the implementation that I needed for `R CMD config` [here](https://github.com/bnaras/rconfig).

Combining it with the `RHOME` and `InstallationPaths` facilities available here, plus adding a simple `Rscript` for ability would increase its usefulness I think.

If there is interest, I am happy to transfer this over to `extendr` and continue development. Please let me know.

**Comment by CGMossa** [comment]
There are several limitations in the current Rust ecosystem to "inherit" configurations from one `build.rs` to another. Furthermore I've spent extensive effort attempting to bind the R-API headers onto a more idiomatic rust representation, and it has not been successful. We won't be doing this at this time unfortunately.
