### ISSUE TITLE
`commit_generated_bindings` warning 

### ISSUE THREAD

**Issue by CGMossa** [extendr/libR-sys#198]
>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/download-artifact@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

This was under Actions, see screenshot: 
![image](https://github.com/extendr/libR-sys/assets/1063624/c18c333e-e402-47ce-bf5a-e1817e7fc314)

**Comment by yutannihilation** [comment]
Thanks for catching. Let's bump the version.
