### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by clauswilke** [extendr/libR-sys#20]
I'd like to release a version 0.2.0 that provides a minimally viable product on all platforms. Below is the checklist for the release. If I'm forgetting anything, please let me know in the comments.

* [x] Address all issues/PRs in the 0.2.0 milestone
* [x] Bump version to 0.2.0
* [x] Tag release on github
* [x] Release to crates.io

**Comment by clauswilke** [comment]
I have changed the expected version for release to 0.2.0, because #27 will add substantial new capabilities that deserve the version bump.

**Comment by clauswilke** [comment]
Are we Ok with releasing the current github master to crates.io as 0.2.0? I believe none of the outstanding issues need to be addressed for a release, so I'd like to go ahead and do this. If I'm missing anything, please let me know by tomorrow, Tues. 12/22/2020.

**Comment by clauswilke** [comment]
@andy-thomason @yutannihilation @Ilia-Kosenkov Just wanted to ping you directly to make sure you have no concerns about releasing the current version of libR-sys to crates.io.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
I have nothing against, it will be to finally pull fixed `libR-sys` from crates.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
I have nothing against, it will be nice to finally pull fixed `libR-sys` from crates.

**Comment by yutannihilation** [comment]
I have no concerns.

**Comment by clauswilke** [comment]
This has been done. Now making sure extendr-api still builds. I love that cargo is strict about versions but sometimes it can get in the way.

**Comment by clauswilke** [comment]
All tests pass.
