### ISSUE TITLE
cargo test fails on linux, OK on mac

### ISSUE THREAD

**Issue by ssh352** [extendr/libR-sys#218]
<img width="1471" alt="Screenshot 2024-02-04 at 10 20 34" src="https://github.com/extendr/libR-sys/assets/41779116/af906807-c0a0-444f-84e7-aa43c1f4d5ee">

cargo build is ok for both linux and Mac though.

Please advise. Thanks!

**Comment by Ilia-Kosenkov** [comment]
Hi. The error says `libR.so` is missing. This is basically R library, and we determine it's location in `build.rs` during build time, but this configuration does not translate to test stage (peculiarities of `cargo`). So just add this library to library search paths or to just path and it should work.

**Comment by yutannihilation** [comment]
I think this isn't the case this time, but just in case, it's possible that there's actually no `libR.so` depending on the build configuration of R.

cf., https://stat.ethz.ch/pipermail/r-package-devel/2023q3/009319.html

**Comment by Ilia-Kosenkov** [comment]
I did not know. So how do we proceed in such environments? How do you link anything to R?

**Comment by yutannihilation** [comment]
> So how do we proceed in such environments?

Simply, you cannot run `cargo test`.

> How do you link anything to R?

I'm not sure, but probably the symbols are searched on runtime...? But, anyway, you don't need to link to R when compiling a staticlib from Rust code.

**Comment by ssh352** [comment]
> Hi. The error says `libR.so` is missing. This is basically R library, and we determine it's location in `build.rs` during build time, but this configuration does not translate to test stage (peculiarities of `cargo`). So just add this library to library search paths or to just path and it should work.

adding to LD_LIBRARY_PATH worked, thanks!

**Comment by Ilia-Kosenkov** [comment]
I am closing this issue as resolved. If you face other problems, please file a new one.
