### ISSUE TITLE
Compilation error: "The system cannot find the path specified"

### ISSUE THREAD

**Issue by etiennebacher** [extendr/libR-sys#219]
Hello, I've updated R from 4.3.2 to 4.3.3 a few days ago and it seems I messed up somewhere because `libR-sys` doesn't find R anymore. When I compile my project, I now get this error:

```
error: failed to run custom build command for `libR-sys v0.6.0`

Caused by:
  process didn't exit successfully: `C:\Users\[PATH]\src\rust\target\debug\build\libR-sys-1599a55cdcbef728\build-script-build` (exit code: 1)
  --- stdout
  Problem locating local R install: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
```

I'm on Windows, running Powershell and without admin rights (in case it matters). This is weird because the path to the R and Rtools binaries are on PATH:

```pwsh
> $env:path

/bin/x64;C:/rtools43/x86_64-w64-mingw32.static.posix/bin;C:/rtools43/usr/bin;[TRUNCATED];C:\Users\etienne\AppData\Local\Programs\R\R-4.3.3\bin

> which R

/c/Users/etienne/AppData/Local/Programs/R/R-4.3.3/bin/R
```

My R installation works fine otherwise. I tried `cargo clean` and recompiling everything but it doesn't work. Do you have some ideas of the cause of this and some potential solutions?

Thanks

<details>
<summary><code>rustup show</code></summary>

<pre>
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\etienne\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc
nightly-2024-02-03-x86_64-pc-windows-gnu (default)
nightly-2024-02-03-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-2024-02-03-x86_64-pc-windows-gnu (default)
rustc 1.77.0-nightly (bf3c6c5be 2024-02-01)
</pre>
</details>

**Comment by CGMossa** [comment]
Can you print `R_HOME` as well?
