### ISSUE TITLE
Problem locating local R install

### ISSUE THREAD

**Issue by Yunuuuu** [extendr/libR-sys#222]
I run `cargo build` or `cargo build --features use-bindgen` or `LIBCLANG_PATH=/usr/lib/llvm-14/lib cargo build --features use-bindgen`, all fails due to following error.
``` bash
error: failed to run custom build command for `libR-sys v0.6.0 (/home/**/WorkSpace/ProgramProject/libR-sys)`

Caused by:
  process didn't exit successfully: `/home/**/WorkSpace/ProgramProject/libR-sys/target/debug/build/libR-sys-f311228b3869771d/build-script-build` (exit status: 1)
  --- stdout
  cargo:warning=Problem locating local R install: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

My system is `Ubuntu 22.04.4 LTS`
R is in the `PATH`
``` sh
> which R
/usr/bin/R
```

**Comment by CGMossa** [comment]
Can you echo R_HOME?

**Comment by Yunuuuu** [comment]
Thanks for your quickly response. I cannot echo R_HOME, but with following command `R_HOME=/usr/lib/R cargo build`, it return error too:
```
error: failed to run custom build command for `libR-sys v0.6.0 (/home/**/WorkSpace/ProgramProject/libR-sys)`

Caused by:
  process didn't exit successfully: `/home/**/WorkSpace/ProgramProject/libR-sys/target/debug/build/libR-sys-f311228b3869771d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=R_HOME=/usr/lib/R
  cargo:r_home=/usr/lib/R
  cargo:rustc-link-search=/usr/lib/R/lib
  cargo:rustc-link-lib=dylib=R
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  thread 'main' panicked at build.rs:668:51:
  Could not obtain R version: InvalidEnvVar("Cannot find R major version")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by CGMossa** [comment]
Now I'm curious. What version of R is that?

**Comment by Yunuuuu** [comment]
My R verssion was here (`4.3.3`):
```r
[R]> R.version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          4
minor          3.3
year           2024
month          02
day            29
svn rev        86002
language       R
version.string R version 4.3.3 (2024-02-29)
nickname       Angel Food Cake

```

**Comment by Ilia-Kosenkov** [comment]
Assuming you can modify source code, can you sprinkle a couple debug statements? Something like
```rust
println!("cargo:warning={object}");
```
In `main()` of `build.rs`. We are interested in paths and R versions that get inferred prior to the error you experience. You might need to pass `-vv` to your `cargo build` as well to get more details in the output.

https://github.com/extendr/libR-sys/blob/fbeceb5904f401c303ef3eee4c5157126856c17c/build.rs#L637-L675

**Comment by Yunuuuu** [comment]
It seems `stdout()` of `cat` and `write` cannot be accepted by rust:

Following code snippet only show `write` function (I have also try `cat`, both gave the same result):
```rust
use std::process::Command;

fn main() {
    let out = Command::new("/usr/lib/R/bin/R")
    .args(
        ["-s", "-e", 
        r"write(sprintf('%s.%s%s\n', R.version$major, R.version$minor, if(isTRUE(grepl('devel', R.version$status, fixed = TRUE))) '-devel' else ''), stdout())",]
    )
    .output()
    .expect("failed to execute process");
    println!(
        "cargo:r_version={}",
        String::from_utf8(out.stdout).unwrap()
    );
}
```

Here is the output:
![image](https://github.com/extendr/libR-sys/assets/19575010/69762926-3dd5-44b0-8410-0b767c4a8f4b)

**Comment by Yunuuuu** [comment]
rust capture all `stdout` from R, if user `.Rprofile` contain stdout message, this will fail capture the right string

**Comment by Ilia-Kosenkov** [comment]
Good catch @Yunuuuu, started CI for your PR

**Comment by CGMossa** [comment]
Yeah, but we need to use another flag. Vanilla is set to be deprecated I
think.. I'll have to check.

**Comment by Yunuuuu** [comment]
`--vanilla` is not tagged as deprecated in R help document, or we should just use `--no-save --no-restore --no-site-file --no-init-file`, R environment file shouldn't contain any stdout information,
![image](https://github.com/extendr/libR-sys/assets/19575010/4cda2c1d-e72a-4e2b-adfe-d5bcf1ed285d)

**Comment by CGMossa** [comment]
I was wrong about `--vanilla` being deprecated. Sorry about that.
