### ISSUE TITLE
non-API calls to R error in R-devel

### ISSUE THREAD

**Issue by eitsupi** [extendr/libR-sys#226]
Today R CMD check for R-devel (2024-04-21 r86458) started getting errors in <https://github.com/pola-rs/r-polars>.
For example:

```log
File 'polars/libs/x64/polars.dll':
  Found non-API calls to R: 'SET_ENCLOS', 'SET_ENVFLAGS', 'SET_PRCODE',
    'SET_PRENV', 'SET_PRVALUE'

Compiled code should not call non-API entry points in R.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
```

<https://github.com/pola-rs/r-polars/actions/runs/8779929721/job/24088871293#step:11:45>

Maybe related to <https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2024/04/21#n2024-04-21>

**Comment by CGMossa** [comment]
Yes! These are new. Usually, our very own @yutannihilation is on top of these when they come up.
They are not located in one place only in the api.
Hopefully, we'll get a hold on this soon.

**Comment by yutannihilation** [comment]
Could you try running this action?

https://github.com/extendr/libR-sys/actions/workflows/non-api-call.yml

**Comment by yutannihilation** [comment]
Wow, a lot!

https://github.com/extendr/libR-sys/pull/227/files

**Comment by CGMossa** [comment]
Can I close this? I think we've dealt with this now, right?
