### ISSUE TITLE
Consider changing this Altrep-interface

### ISSUE THREAD

**Issue by CGMossa** [extendr/libR-sys#232]
Currently, the bindings generate
```rs
pub type R_altrep_Coerce_method_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: SEXP, arg2: ::std::os::raw::c_int) -> SEXP>;
```
in particular, this `c_int`. There is little documentation on it, but this function prototype is satisfied by a function 
that looks like this

```c
static SEXP altrep_Coerce_default(SEXP x, int type) { return NULL; }
```
Thus the second argument is supposed to be a type, presumably `SEXPTYPE`, which we have now made into an `enum`.

**Comment by CGMossa** [comment]
There are no meaningful tests in extendr for `R_altrep_Coerce_method_t`. And I can't find even a coerce method available to use with extendr made altrep objects. We should device a test and see if this abstraction causes an issue.

**Comment by yutannihilation** [comment]
> Thus the second argument is supposed to be a type, presumably `SEXPTYPE`, which we have now made into an `enum`.

I think you are correct. It seems the `Coerce` method is what is called here.

https://github.com/wch/r-source/blob/ab9c4114cd774d359f6d4c3b4a69e7ba9d2864c8/src/main/coerce.c#L1182-L1191
```c
SEXP coerceVector(SEXP v, SEXPTYPE type)
{
    if (TYPEOF(v) == type)
	return v;


    SEXP ans = R_NilValue;	/* -Wall */
    if (ALTREP(v)) {
	PROTECT(v); /* the methods should protect, but ... */
	            /* also "v" is protected by caller */
	ans = ALTREP_COERCE(v, type);
```

**Comment by CGMossa** [comment]
Now I get it. So for extendr, one has to call the altrep as an Robj to invoke it. I needed this information, many times thanks!
