### ISSUE TITLE
Support for R_xlen_t on 32-bit systems

### ISSUE THREAD

**Issue by clauswilke** [extendr/libR-sys#28]
The long vector length type `R_xlen_t` is typedef'd to `ptrdiff_t` on 64-bit systems but to `int` on 32-bit systems: 
https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/include/Rinternals.h#L71-L78
This trips up bindgen, which translates `ptrdiff_t` to `isize` and `int` to `::std::os::raw::c_int`, and then Rust rightfully recognizes that these two types are not the same, and then complains in code such as this one:
https://github.com/extendr/extendr/blob/41772722a01062b064320c98d687e3eae889790a/extendr-api/src/robj.rs#L2032-L2034

This will have to be addressed somewhere, either in libR-sys by special-casing `R_xlen_t` or in extendr by never assuming that `R_xlen_t` is `isize`.

@andy-thomason Thoughts on whether the right place to address this is libR-sys or extendr? You have a lot of code converting `isize` into `usize` in extendr, which makes me think fixing this in libR-sys is the preferred solution, but there may be something I'm missing.

**Comment by lebensterben** [comment]
I don't use libR-sys in my own project because it isn't portable. Bindgen is not able to deal with many c macros.

The right way to deal with this is to generate R's C bindings in extendr's build.rs
