### ISSUE TITLE
GitHub Actions cache

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#37]
I am not sure how it works, but after updating GitHub actions I noticed two things.
First, we install `msys2/mingw64` for both `x86_64` and `i686` builds 
https://github.com/extendr/libR-sys/blob/12511006ccf62dcf298389ee2baa1cd562a700f1/.github/workflows/test.yml#L78-L82
And it works. If `msys2` bundles both `mingw32`/`mingw64`, I am not quite sure what does the `msystem` flag control (see [msys2 actions](https://github.com/msys2/setup-msys2)).

Second, I don't know what is `r` that is installed via `brew` on `MacOS`
https://github.com/extendr/libR-sys/blob/12511006ccf62dcf298389ee2baa1cd562a700f1/.github/workflows/test.yml#L114-L119

If anyone has more expereince with GHA than I do, please clarify what is going on and how can we test dependencies.

**Comment by clauswilke** [comment]
`msystem` just sets some default paths. You may be working around all those path settings anyways, but setting it to `MINGW32` for the 32-bit build is probably more appropriate.

R should not be installed via `brew`, I missed this. Can you just remove it?

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
Yes, I will, I am currently trying to understand what is happening under the hood of `msys2`.
For `mingw32`/`mingw64` I suggest to use an extra config key `msystem` present on `Windows` machines only.
https://github.com/Ilia-Kosenkov/libR-sys/blob/629c0f1da53066ceabda3a0f8f498d43690d6d30/.github/workflows/test.yml#L25-L34
https://github.com/Ilia-Kosenkov/libR-sys/blob/629c0f1da53066ceabda3a0f8f498d43690d6d30/.github/workflows/test.yml#L74-L82

My experiments showed that both `mingw32` and `mingw64` are present, so it probably affects `msys2` shell but not our manual environment setup.

I will also remove `r` from `brew`

**Comment by Ilia-Kosenkov** [comment]
Resolved with #38
