### ISSUE TITLE
Enabling Win-i686 tests

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#39]
Currently, bindgen layout tests are disabled for Windows x86
https://github.com/extendr/libR-sys/blob/80488ec76147ae367de8d8050107998771dcfb3f/build.rs#L260-L263

There are two failing layout tests out of 19 actually, and I found similar issues, for instance, https://github.com/rust-lang/rust-bindgen/issues/1823. This issue was not resolved, because the problem itself is severe: https://github.com/rust-lang/rust/issues/54341, if I understand correctly, `LLVM` produces incorrect (or different) alignment for `int128`/`float128` types.

We can enable the majority of tests if we blacklist `max_align_t` (mentioned in `rust-lang` issue) and `__mingw_ldbl_type_t`, which, I assume, is `long double`, which is misaligned in `LLVM`. 
This also means that any usage of these types is unsafe as they are not ABI compatible with `C` counterparts, but I am not sure how widely they are used.

**Comment by clauswilke** [comment]
Sure, why don't you try to disable these two types and see what happens. I doubt we use them in libR-sys or downstream, and if we do we need to get them right anyways.

**Comment by clauswilke** [comment]
Honestly, I have never felt good about disabling the layout tests, because it says we know something is wrong and we just choose to ignore it and cross our fingers. Better to just avoid the problematic types or find a viable workaround, like I had to do for `R_xlen_t`.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
Already did, it is working.
https://github.com/Ilia-Kosenkov/libR-sys/runs/1597170309?check_suite_focus=true#step:10:1077
https://github.com/Ilia-Kosenkov/libR-sys/blob/e41221ea8c4d8c4419d80c0c6a20cb120812f1de/build.rs#L260-L268

Have a PR ready if it is reasonable

**Comment by clauswilke** [comment]
Yes, a PR would be great. Just keep in mind that this means all affected precomputed bindings should be replaced. We need to automate that last step at some point. Also, please add your name to the authors in `Cargo.toml` and `LICENSE`, at the end of the current list.

**Comment by clauswilke** [comment]
I say let's close this issue and open a new one if and when problems arise.
