### ISSUE TITLE
[Windows] MSYS2 appears to be part of the image

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#41]
If I understand [this listing](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) correctly, `MSYS2` is bundled with the `windows-latest` image, but it is not added to the `PATH`.
Since we configure `MSYS2` paths ourselves, it appears we do not need `MSYS2` installation step.
Assuming it is not affected by caching, it works fine without it, see 
https://github.com/Ilia-Kosenkov/libR-sys/runs/1606864716

This may save us about 10-12 seconds, which is not much, but if I am correct, we just waste resources each time.
Again, if this is true, other build pipelines (at least, `extendr`) are also affected.

**Comment by clauswilke** [comment]
If you give the run a new name the cache gets cleared. In this way you can check whether caching matters.
