### ISSUE TITLE
Releasing `aarch64` bindings for Apple Silicon

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#46]
I see that `extendr` depends on crates version of `libR-sys`. 
https://github.com/extendr/extendr/blob/9752c7f73c109bef321e17d2cdba3f332153d7b7/extendr-engine/Cargo.toml#L11
To continue testing `aarch64`, we need to either release something like `libR-sys v0.2.1` or link `extendr` against dev (github) version of `libR-sys`, which is not a good thing.
Do we have any breaking changes since `0.2.0`? From what I see in history commits are either CI or documentation improvements.

**Comment by clauswilke** [comment]
I think we should wait until #44 is merged and then release 0.2.1.

**Comment by clauswilke** [comment]
Closing in favor of #48.
