### ISSUE TITLE
Release version 0.2.1

### ISSUE THREAD

**Issue by clauswilke** [extendr/libR-sys#48]
Version 0.2.1 will have precompiled bindings for Apple Silicon.

* [x] Merge #47  
* [x] Update version number in changelog 
* [x] Bump version to 0.2.1
* [x] Tag release on github
* [x] Release to crates.io

**Comment by clauswilke** [comment]
Any objections to me releasing the current version of libR-sys as 0.2.1? @andy-thomason @Ilia-Kosenkov

**Comment by Ilia-Kosenkov** [comment]
No, please proceed.

**Comment by clauswilke** [comment]
Done.
