### ISSUE TITLE
crate name conflicts with system library

### ISSUE THREAD

**Issue by lebensterben** [extendr/libR-sys#5]
I built a Rust library that exposes C API to R, using `libR-sys`.
It turns out that
- I can built it directly with `cargo`
- But if I tried to build it within R/Rstudio, I will keep getting
  `error: linking with `cc` failed: exit code`
  for `libR-sys` crates

I found this [issue](https://github.com/rust-lang/rust/issues/25289#issuecomment-101352844), where someone pointed out the possible cause is
> In this case foo is portaudio for you, but you're both generating a dynamic library called libportaudio.so and linking against (I presume) the system libportaudio.so. Unfortunately these names are the same, so the linker appears to be creating the output libportaudio.so file first, and then attempting to link that in (but it errors because it's invalid).

I'm not sure why this still occurs, but I forked this crate and changed its name to `rbindings`, then everything works.

**Comment by andy-thomason** [comment]
It would be useful to have full reproduction steps for this. I'm unfamiliar with RStudio.

Alex's issue seemed to be around  generating a conflicting .so file name and libR-sys does not generate one
as it is a standard Rust crate (although it does *use* one from the system environment).

libR-sys is the correct Rust name for the sys binding (including the capital R). Docs.rs was a bit confused
by the name, too and had to be fixed.

**Comment by andy-thomason** [comment]
We will probably have to address issues with RStudio down the line. But  I'm closing this for now.
