### ISSUE TITLE
[Windows] [CI] Use Rtools to test pre-computed bindings

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/libR-sys#53]
This is a reminder to update CI workflow
https://github.com/extendr/libR-sys/blob/ccdf5d57071ee058b3ed5d7cd62054204e11c722/.github/workflows/test.yml#L264-L266
in light of the recent merging of this PR https://github.com/r-windows/rtools-packages/pull/186.

The problem on Windows side is that MSYS2 (used for generating bindings), Rtools (custom MSYS2 build) and mingw toolchains in rust's `*pc-windows-gnu` ship different versions of gcc and friends. This creates issues that can be resolved using hacks (see code snippet above).
In particular, in PR https://github.com/r-windows/rtools-packages/pull/186 we suggested implementing a hack that was present in 32-bit version of Rtools, but not in 64-bit version.
As soon as updated rtools gets released (I believe it will take significant time), we can update CI here. I hope with Rtools patched we may be able to move additional workflows to Rtools only, avoiding both MSYS2 and rust's own `mingw` tools.

**Comment by clauswilke** [comment]
Could you remind us what exactly will have to be changed, so this info doesn't get lost between now and when the next Rtools is available?

**Comment by Ilia-Kosenkov** [comment]
It is easy: in the linked code snippet this line should be removed:
```
cp C:\rtools40\mingw64\lib\gcc\x86_64-w64-mingw32\8.3.0\libgcc.a C:\rtools40\mingw64\lib\gcc\x86_64-w64-mingw32\8.3.0\libgcc_eh.a  
```
Right now it creates a fake copy of `libgcc_eh.a`, because Rtools ships none for x64 version (but this lib is required for compilation). With the new Rtools release, this file will be a part of Rtools so there is no need to manually create a copy.
