### ISSUE TITLE
Bindings for R 4.1

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#57]
Sorry, I forgot how to update bindings. Do we need to do this? Or should the unversioned bindings (e.g. `bindings-linux-x86_64.rs`) just work?

**Comment by andy-thomason** [comment]
It would be worth documenting how to make a new "pre-baked" R version set of bindings.

I would imagine you could build with the "use-bindgen" feature and copy the resulting rust file from `target/`

The function `retrieve_prebuild_bindings` in build.rs will select any appropriate rust version if it exists
without modification.

**Comment by andy-thomason** [comment]
For 4.1 the only difference is the exposure of R_NewEnv, it seems. This would be nice to have but should not impact
anything in the current version.

**Comment by yutannihilation** [comment]
Ah, thanks for the hints! This worked on my local Ubuntu:

``` sh
export LIBRSYS_BINDINGS_OUTPUT_PATH="$(pwd)/bindings"
export LD_LIBRARY_PATH="$(R -s -e 'cat(normalizePath(R.home()))')/lib"
cargo build --features use-bindgen
```

**Comment by yutannihilation** [comment]
Okay, I remembered... Precompiled binaries are available as the artifacts of GitHub Actions CI after this pull request:

https://github.com/extendr/libR-sys/pull/27

**Comment by yutannihilation** [comment]
Here's diffs of the bindings, which I created by using GitHub Actions (see https://github.com/extendr/libR-sys/pull/58).

https://github.com/yutannihilation/libR-sys/pulls

**Comment by clauswilke** [comment]
Yes, I had originally envisioned that we would update the bindings with every major release of R. There are a couple of problems we haven't solved yet:

- We currently generate bindings automatically, but updating the bindings requires manual work. Can it be automated also?
-  Do we make a new release to crates.io every time we update bindings? If so, how exactly do we change the version number (major, minor, patch)?
- Do we delete old bindings for R versions that aren't part of our CI anymore?

**Comment by yutannihilation** [comment]
Thanks.

> Can it be automated also?

I found we can use `hub` command to create pull requests: https://github.com/extendr/libR-sys/pull/58

> Do we make a new release to crates.io every time we update bindings?

I don't think so. Maybe we can release only when there's some problem with the existing bindings. But the problem is that this cannot be detected by CI after we update the bindings to the latest...

**Comment by yutannihilation** [comment]
> Do we delete old bindings for R versions that aren't part of our CI anymore?

I feel we should delete. I think, in practice, we support only "release" and "oldrel", considering the older versions than "oldrel" is not tested on CI. So we should be clear about this, though we might change our policy to support more versions in future.
