### ISSUE TITLE
Can we export `R_NewEnv`?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#65]
I found extendr currently calls R function `new.env()` to create a new environment. 

``` rust
let robj = call!("new.env", TRUE, parent, dict_len).unwrap();
```
https://github.com/extendr/extendr/blob/9bd098875139aa91ea9b3961dbef895974dd5d34/extendr-api/src/wrapper/environment.rs#L65

I'm not familiar with how to handle environments with C, but I guess this can be directly done by C function `R_NewEnv`, which is under the hood of `new.env()`. But, currently it seems the function is not exported. Can we export this function?

**Comment by yutannihilation** [comment]
Aw, okay, I got it. It's exported only on R >=4.1. This isn't a very important issue, but would be nice example to think about how we should handle the differences between versions...

```
❯ git grep -l R_NewEnv
bindings/bindings-linux-x86_64-R4.1-devel.rs
bindings/bindings-linux-x86_64-R4.1.rs
bindings/bindings-linux-x86_64-R4.2-devel.rs
bindings/bindings-macos-aarch64-R4.1.rs
bindings/bindings-macos-x86_64-R4.1-devel.rs
bindings/bindings-macos-x86_64-R4.1.rs
bindings/bindings-macos-x86_64-R4.2-devel.rs
bindings/bindings-windows-x86-R4.1-devel.rs
bindings/bindings-windows-x86-R4.1.rs
bindings/bindings-windows-x86-R4.2-devel.rs
bindings/bindings-windows-x86_64-R4.1-devel.rs
bindings/bindings-windows-x86_64-R4.1.rs
bindings/bindings-windows-x86_64-R4.2-devel.rs
```

**Comment by clauswilke** [comment]
Yes, I thought it was a recently added function. It's really quite surprising that until 4.1 you couldn't generate a new environment from C.

**Comment by yutannihilation** [comment]
Yeah, it's really surprising... I found the commit, but it seems there's no NEWS item on changelog.

https://github.com/wch/r-source/commit/8a322e786068ec2e23324e61821ff666d0b6e329

**Comment by yutannihilation** [comment]
As https://github.com/extendr/extendr/pull/228 succeeded to work both on R >=4.1.0 and <4.1.0, it turned out this aren't the problem on libR-sys's side (except that the version is not published to crates.io yet). I'm closing this.
