### ISSUE TITLE
Document DEP_* environmental variables

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#67]
Currently libR-sys provides these environmental variables, which is useful to use in build scripts when we want to change configuration depending on the R versions (e.g. [an example on the Cargo Book](https://doc.rust-lang.org/cargo/reference/build-script-examples.html#conditional-compilation), and [the actual usage on extendr](https://github.com/extendr/extendr/pull/228)). We should document these variables properly.

https://github.com/extendr/libR-sys/blob/7418fade4bca9723ac1c1382c5d570a0fdb083c8/build.rs#L220-L228
https://github.com/extendr/libR-sys/blob/7418fade4bca9723ac1c1382c5d570a0fdb083c8/build.rs#L384

**Comment by yutannihilation** [comment]
Oh, good point, thanks. I'll check later, but probably you are right and we should forward them.

**Comment by andy-thomason** [comment]
:+1:

**Comment by yutannihilation** [comment]
Closed via https://github.com/extendr/libR-sys/commit/7cc6c2e6dd28c9c653fbec5d34990d55eed670f0 (accidentally committed to master again, sorry...)

**Comment by clauswilke** [comment]
@yutannihilation You wrote "extendr crate" but I think you mean "the libR-sys crate"

**Comment by yutannihilation** [comment]
Aw, yes.... Thanks for catching.

**Comment by yutannihilation** [comment]
I included the fix in #73
