### ISSUE TITLE
Windows with UCRT toolchain

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#79]
I'm not sure if it would generate different bindings, but we might need to check if this works, at least.

* Document: https://github.com/r-windows/docs/blob/master/ucrt.md
* The latest update on R-devel mailing list: https://stat.ethz.ch/pipermail/r-devel/2021-August/081020.html

**Comment by Ilia-Kosenkov** [comment]
I think we need to at least explore. Have you tried to build something using `ucrt` toolchain?

**Comment by yutannihilation** [comment]
Yes, it seems the extendr stuffs work fine with ucrt toolchain as well at least on simple cases. Here's my attempt:

https://github.com/yutannihilation/string2path/pull/10/files

I don't try generating the bindings yet, though.

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation, honestly I do not understand how it works :) 
I doubt we need differently-generated bindings, if R headers are the same, then bindings are the same as well.
It is hard to grasp the output of the CI, I am in the process of installing a local copy of `ucrt`-compatible `R`, will do some basic `{rextendr}` examples and see how it goes. 

If it works as-is though, these are greate news!

**Comment by Ilia-Kosenkov** [comment]
So, surprisingly, it works out of the box. I created a sample package and observed that it was compiled targeting `x86_64-pc-window-gnu` yet with includes coming from `ucrt64`, which is nice.
In the same setup I also made the following reprex:

```r

 # Makes sure the package library is devel
 Sys.setenv(R_LIBS_USER = "C:/Users/[redacted]/R/win-library-devel/4.0")
 .libPaths(Sys.getenv("R_LIBS_USER"))

 rextendr::rust_function(r"(fn say_hello(name : String) -> String { format!("Hello, {}!", name).to_string() })")
#> ℹ build directory: 'C:\Users\[redacted]\AppData\Local\Temp\Rtmp0KSIX2\filec9c4bbe220a'
#> ✔ Writing 'C:/Users/[redacted]/AppData/Local/Temp/Rtmp0KSIX2/filec9c4bbe220a/target/extendr_wrappers.R'.

 say_hello("Ilia") # Worked before
#> [1] "Hello, Ilia!"
 say_hello("Илья") # Did not work before
#> [1] "Hello, Илья!"

```

There are very few issues with UTF-8 support on windows now (running non-Cyrillic encoding in the system by default).
Now that I think of it, the reprex may be misleading -- we inject path to Rtools when building rust code at runtime
https://github.com/extendr/rextendr/blob/31c3cd331b0923f17da22c0f27d2168c2014f1e7/R/source.R#L260-L280
Perhaps we should now provide an option to use `ucrt64` instead of `mingw64` on Windows?

For instance, here
https://github.com/extendr/libR-sys/blob/a5979b64068932bc9fbc6855efebc8922dcbb635/.github/workflows/test.yml#L250-L263

We can simplify this code and add another case for `x86_64-ucrt`.

**Comment by yutannihilation** [comment]
Thanks for investigating! Great! :tada: 

>  I doubt we need differently-generated bindings, if R headers are the same, then bindings are the same as well.

Ah, probably you are right. 

>  Perhaps we should now provide an option to use `ucrt64` instead of `mingw64` on Windows?

Can it be distinguished by `R.version`? I think it shouldn't be an option. Users need to use the same toolchain that is used for compiling the R itself, if I understand correctly.

**Comment by Ilia-Kosenkov** [comment]
No idea if it can be distinguished at runtime. Perhaps using encodings (it was mentioned at one of your links), but I don't know how reliable it is.

So, when we compile a package, Rtools gets injected the usual way (by R compilation tool chain), so we do not need to do anything. But when we compile function dynamically, we add Rtools ourselves. Right now I think there is a flag in rextendr to switch of Rtools injection, I will suggest to replace it with enum to distinguish between  `mingw`
 and `ucrt`

**Comment by yutannihilation** [comment]
> So, when we compile a package, Rtools gets injected the usual way (by R compilation tool chain), so we do not need to do anything. But when we compile function dynamically, we add Rtools ourselves.

I see. It's a bit complicated because we need `ucrt` toolchain _in addition to_, not instead of, `mingw64`, at least at the moment.

> Unlike the regular R, the experimental R-devel builds look for gcc on the PATH, so you need to add e.g. `c:/rtools40/ucrt64/bin` to the PATH, in addition to the regular `make` tools from `c:/rtools40/usr/bin`.
(<https://github.com/r-windows/docs/blob/master/ucrt.md#testing-packages-with-ucrt64-using-rtools4>)

I guess this is temporary and we'll see more easier way to deal with UCRT toolchains until the actual release. So, it's probably good to wait for a while because the direction is yet to be determined.

https://stat.ethz.ch/pipermail/r-devel/2021-August/081020.html
https://stat.ethz.ch/pipermail/r-devel/2021-August/081030.html

**Comment by yutannihilation** [comment]
It seems the support for UCRT toolchain is comming on r-lib/actions.

https://github.com/r-lib/actions/pull/371

**Comment by yutannihilation** [comment]
Closing in favor of https://github.com/extendr/extendr/issues/396
