### ISSUE TITLE
libR-sys fails to obtain R-version on conda-forge osx-arm64

### ISSUE THREAD

**Issue by mlondschien** [extendr/libR-sys#85]
The conda-forge builds for my package (r-)changeforest fails due to
```
error: failed to run custom build command for `libR-sys v0.2.2`

Caused by:
  process didn't exit successfully: `/Users/runner/miniforge3/conda-bld/r-changeforest_1641818835367/work/changeforest-r/src/./rust/target/release/build/libR-sys-7ac94a74d09fbe03/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=R_HOME=/Users/runner/miniforge3/conda-bld/r-changeforest_1641818835367/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R
  cargo:r_home=/Users/runner/miniforge3/conda-bld/r-changeforest_1641818835367/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R
  cargo:rustc-link-search=/Users/runner/miniforge3/conda-bld/r-changeforest_1641818835367/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/lib
  cargo:rustc-link-lib=dylib=R
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  thread 'main' panicked at 'Could not obtain R version: Custom { kind: Other, error: "Cannot find R major version" }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libR-sys-0.2.2/build.rs:393:56
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makevars:11: rust/target/release/libchangeforest.a] Error 101
ERROR: compilation failed for package ‘changeforest’
* removing ‘/Users/runner/miniforge3/conda-bld/r-changeforest_1641818835367/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/library/changeforest’
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/r-changeforest_1641818835367/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

Sadly, I currently cannot reproduce this locally.

Build log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=438640&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445
osx-arm64 migration PR: https://github.com/conda-forge/r-changeforest-feedstock/pull/4

Any hunch what might be happening here?

**Comment by Ilia-Kosenkov** [comment]
So R is looked up here https://github.com/extendr/libR-sys/blob/ee52284663067bf41de154f41d404b05da626665/build.rs#L71.
I wonder why do you even hit libR-sys compilation phase when we provide pre-compiled bindings for arm64 mac os. What is your local machine configuration? Do you also observe libR-sys compilation (especially if you run arm64)?

**Comment by Ilia-Kosenkov** [comment]
Attempt # 2 to address this. So the problem arises here https://github.com/extendr/libR-sys/blob/ee52284663067bf41de154f41d404b05da626665/build.rs#L167.
I wonder if the path to R_HOME is correct, it looks weird. Also, is it possible to execute this fragment in the environment and observe its output in the logs?
https://github.com/extendr/libR-sys/blob/ee52284663067bf41de154f41d404b05da626665/build.rs#L177-L183

**Comment by andy-thomason** [comment]
I'm guessing that it finds R or the `Command` would fail.

It would be interesting to see details of the string this returns. I'm wondering if the Conda version
adds some extra characters, just for badness.

**Comment by mlondschien** [comment]
I installed R via conda.

On osx-arm64:
```r
> R.version
               _                           
platform       aarch64-apple-darwin20.0.0  
arch           aarch64                     
os             darwin20.0.0                
system         aarch64, darwin20.0.0       
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
> v <- strsplit(R.version$minor, '.', fixed = TRUE)[[1]];devel <- isTRUE(grepl('devel', R.version$status, fixed = TRUE));cat(R.version$major, v[1], paste0(v[2:length(v)], collapse = '.'), devel, R.version$version.string, sep = '\n')
4
1
2
FALSE
R version 4.1.2 (2021-11-01)
```

**Comment by xhochy** [comment]
One important thing to note here is that the referenced build from @mlondschien here is a cross-compiled R package installation. In that case, two R installations exist. One for R on x86 and one for R on ARM. The CI is run on x86 but the package will be built for ARM. As this is an x86 instance, it cannot run the ARM binaries. The cross-compilation works as normally the Intel-`R` binary is called and paths are setup in a way that it will built everything with ARM as a target. In the referenced snippet above, it uses `R_HOME` to find the `R` binary. This is the ARM one and not executable on CI. The build scripts above set an `R` environment variable that link to the runnable `R` binary. This has been working for nearly all R packages we cross-compiled yet. It would be nice if that would also be checked.

@mlondschien It is probably running locally for you, as you build either not in cross-compiling mode or if you are compiling in cross-compiling mode, on an Apple M1, you can run both, x86 and ARM binaries.

**Comment by mlondschien** [comment]
Thanks @xhochy. This makes a lot more sense now! So this could be fixed by replacing

```rust
        Path::new(&r_paths.r_home)
            .join("bin")
            .join("R")
    };
```
with
```rust
use std::env;

...

r_binary = match r_env::var("R") = {
    Ok(r_binary_path) => Path::new(r_binary_path),
    Err(_) => Path::new(&r_paths.r_home).join("bin").join("R")
}
```

**Comment by Ilia-Kosenkov** [comment]
> The build scripts above set an R environment variable that link to the runnable R binary.

I am not sure `R` is a standard environment variable, is its usage described somewhere on CRAN?
If not, tying build script to one particular third-party solution is not a good approach IMO.

If `R` is commonly used (which I am unaware of), we can definitely check for it as well. Alternatively, we can check for `R_BINARY_PATH` or something like that, which can be set to an adequate value depending on the platform/runner used for building.

**Comment by mlondschien** [comment]
I don't know what CRAN does. IIUC they don't support rust at all currently. If `libR-sys` would check for `R_BINARY_PATH`, we could set this variable on the conda runner.

**Comment by Ilia-Kosenkov** [comment]
Maybe it is not the correct approach here. It seems that conda runner's environment is configured for arm64 version (e.g., its `R_HOME` points there), so whatever paths to library or headers we determine should be correct. We invoke `R` to get its version, and here it fails because we try to call arm64 binary which is obviously incompatible. Perhaps the better approach would be to recognize `R_VERSION` or something like that, which again can be set manually for the runner (or even dynamically). `R_VERSION` could provide us all the necessary information to determine what type of bindings should be used, e.g. `4.1.0`

As a result, if `R_HOME` and `R_VERSION` are set, no R executable will be called and compilation should proceed just fine.

**Comment by mlondschien** [comment]
If R is only called to get the R version, this would work perfectly.

**Comment by yutannihilation** [comment]
> Perhaps the better approach would be to recognize `R_VERSION` or something like that, which again can be set manually for the runner (or even dynamically)

This sounds good to me.

**Comment by Ilia-Kosenkov** [comment]
I will try to draft PR later today and check if `R_VERSION` is a good solution.

**Comment by andy-thomason** [comment]
That sounds good. It would be good to have an override.

**Comment by Ilia-Kosenkov** [comment]
@mlondschien, #87 should help you solve your issue. Can you point your package to the dev version of `libR-sys`?

**Comment by Ilia-Kosenkov** [comment]
I guess it is not that easy. Perhaps you can have a custom fork of `extendr` where you uncomment https://github.com/extendr/extendr/blob/master/Cargo.toml `patch.crates-io` and then point your R package to your fork. That way I think it should pull all dev versions.

**Comment by mlondschien** [comment]
I made a fork and uncommented the patch as you suggested: https://github.com/mlondschien/extendr/commit/42f2b96ea1d5650b8f137d3d33d2a9f2806d02d3.
Here I point the `Cargo.toml` of the R package towards that fork: https://github.com/conda-forge/r-changeforest-feedstock/blob/65b8853c5ecdfb4de2f3aaf0f472486d02c321ce/recipe/build.sh.

On linux:
```
error[E0599]: no method named `dollar` found for reference `&'a extendr_api::Robj` in the current scope
  --> src/control.rs:13:14
   |
13 |             .dollar("minimal_relative_segment_length")
   |              ^^^^^^ method not found in `&'a extendr_api::Robj`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
...
```
Did the API change?

On OSX:
```
error: failed to run custom build command for `libR-sys v0.2.2`

Caused by:
  process didn't exit successfully: `/Users/runner/miniforge3/conda-bld/r-changeforest_1642544522311/work/changeforest-r/src/./rust/target/release/build/libR-sys-e8701c5900641bf4/build-script-build` (exit status: 101)
  cargo:rustc-env=R_HOME=/Users/runner/miniforge3/conda-bld/r-changeforest_1642544522311/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R
  cargo:r_home=/Users/runner/miniforge3/conda-bld/r-changeforest_1642544522311/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R
  cargo:rustc-link-search=/Users/runner/miniforge3/conda-bld/r-changeforest_1642544522311/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/lib
  cargo:rustc-link-lib=dylib=R
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  thread 'main' panicked at 'Could not obtain R version: Custom { kind: Other, error: "Cannot find R major version" }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libR-sys-0.2.2/build.rs:393:56
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makevars:11: rust/target/release/libchangeforest.a] Error 101
ERROR: compilation failed for package ‘changeforest’
* removing ‘/Users/runner/miniforge3/conda-bld/r-changeforest_1642544522311/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/library/changeforest’
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/r-changeforest_1642544522311/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
Finishing: Run OSX build
```

The patch may not have worked. Suggestions?

**Comment by Ilia-Kosenkov** [comment]
On linux it seems it is getting some older version.
On mac you can see you are still referencing crates.io `0.2.2` version 
> `libR-sys v0.2.2`

Perhaps it was not enough to just uncomment patch. Let me reproduce it with a fork to make sure it works as intended.

**Comment by Ilia-Kosenkov** [comment]
Due to #89 right now it will not work correctly, yet in your case something seems to be misconfigured. 
> thread 'main' panicked at 'Could not obtain R version: Custom { kind: Other, error: "Cannot find R major version"
This error message is obsolete, in the new version of libR-sys it should look like this (if env var is incorrect)
```
thread 'main' panicked at 'Could not obtain R version: InvalidEnvVar("Cannot find R major version")'
```
Or `RInvocationError(...)` or `InvalidROutput` if the problem arises from the R executable.

So if I modify `Cargo.toml` to
```
[patch.crates-io]
libR-sys = { git = "https://github.com/Ilia-Kosenkov/libR-sys", branch = "fix-r-version-env" }
```

It seems to work fine.

**Comment by yutannihilation** [comment]
Sorry, we found a problem to use `R_VERSION`, so it's now changed to `LIBR_SYS_R_VERSION`.

**Comment by mlondschien** [comment]
Thanks a lot! I just merged https://github.com/conda-forge/r-changeforest-feedstock/pull/4, so feel free to close.
