### ISSUE TITLE
libR-sys fails to detect the R version with R-devel?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#88]
I'm seeing this error on https://github.com/extendr/extendr/pull/360, but there actually are these fields in the bindings file: https://github.com/extendr/libR-sys/blob/4a8734e3a1e40500f95669622af041d4a97d1a9d/bindings/bindings-linux-x86_64-R4.2-devel.rs#L6393

```
error[E0560]: struct `_DevDesc` has no field named `defineGroup`
   --> /home/runner/work/extendr/extendr/extendr-api/src/graphics/device_descriptor.rs:696:13
    |
696 |             defineGroup: self.defineGroup,
    |             ^^^^^^^^^^^ `_DevDesc` does not have this field
    |
    = note: available fields are: `left`, `right`, `bottom`, `top`, `clipLeft` ... and 70 others
```

Apart from this, I also see some weird behavior when compiling with R-devel on my Windows machine. The problem here is that it seems the R-devel now doesn't set the system environment variable `R_HOME` and there's an old one for R 4.1.2.

I'll investigate this.

**Comment by Ilia-Kosenkov** [comment]
I thought so. Would you like to make a PR? `R_VERSION` is explicitly written at the end of the build script and in the `README`.

**Comment by yutannihilation** [comment]
Sure.
