### ISSUE TITLE
`gamma` is not present in the bindings generated for windows

### ISSUE THREAD

**Issue by CGMossa** [extendr/libR-sys#95]
After a little bit of detective work, I see that the files inside `bindings/` that contain `windows` do not have a `extern` block for the `gamma`-function, but this is present in the macos, for instance.

Any way this can be resolved?

**Comment by yutannihilation** [comment]
I think it comes from this header file, which is not an R API.

https://github.com/extendr/libR-sys/blob/355cf0de0dd7f28cfa3933a70b29deb247eb2017/wrapper.h#L1

**Comment by CGMossa** [comment]
Okay; I don't really know how to proceed with this.
It is unfortunate, as I wanted to use this stuff now.

**Comment by clauswilke** [comment]
@CGMossa You should use a Rust-native implementation of the gamma function, e.g. [here](https://docs.rs/special/0.8.1/special/trait.Gamma.html) or [here.](https://docs.rs/statrs/0.8.0/statrs/function/gamma/index.html)

**Comment by yutannihilation** [comment]
For now, lgamma is what you want.

> These functions exist for compatibility reasons. They are equivalent to lgamma etc. It is better to use lgamma since for one the name reflects better the actual computation, and moreover lgamma is standardized in ISO C99 while gamma is not. 
https://www.gnu.org/software/libc/manual/html_node/Special-Functions.html

**Comment by CGMossa** [comment]
Thank you so much for this.

**Comment by yutannihilation** [comment]
I made the list of actual items from R (including non-APIs). I'll create a pull request to see the diff.

https://github.com/yutannihilation/extract-R-API-items-from-header-file/blob/main/dump.txt

**Comment by yutannihilation** [comment]
As the original issue seems to be resolved already (please reopen if not), I'm closing this issue. Let's file another one for #96.
